# Generated by Django 2.2.1 on 2019-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='location',
        ),
        migrations.AddField(
            model_name='song',
            name='location',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
