# Generated by Django 2.2.1 on 2019-10-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.FilePathField(path='/media'),
        ),
    ]
