# Generated by Django 2.2.1 on 2019-10-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191023_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.SlugField(max_length=250),
        ),
    ]
