# Generated by Django 2.2.1 on 2019-10-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191023_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
