# Generated by Django 2.2.1 on 2019-10-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20191023_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='que',
            name='status',
            field=models.CharField(blank=True, choices=[('Ready', 'ready'), ('Playing', 'playing'), ('Paused', 'paused'), ('Stopped', 'stopped')], default='ready', max_length=16),
        ),
    ]
